name: Build Documentation
on:
  push:
    branches:
      - main
  
jobs:
  docs:
    name: Build Circulation-Web Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v2
     
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      
      - name: Install dependencies
        run: npm ci
     
      - name: Build docs
        run: npm run build-docs

# Deploy to http://nypl-simplified.github.io/circulation-web/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs